services:
  webserver:
    build:
      context: .dockers/webserver
    container_name: 'drakkar-ci'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
